import os.path
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

import toml

sphinx_path = Path(__file__).parent.parent
project_path = sphinx_path.parent
src_path = project_path / "src"

source_folders = []

# Get the list of folders in source
if os.path.isdir(src_path):
    for folder in os.listdir(src_path):
        source_folders.append(src_path / folder)

# Clean old builded files
if os.path.isdir(sphinx_path / "build" / "doctrees"):
    shutil.rmtree(sphinx_path / "build" / "doctrees")
if os.path.isdir(sphinx_path / "build" / "html"):
    shutil.rmtree(sphinx_path / "build" / "html")
if os.path.isdir(sphinx_path / "source" / "autoapi"):
    shutil.rmtree(sphinx_path / "source" / "autoapi")

def _load_project_metadata() -> dict[str, Any]:
    pyproject_path = project_path / "pyproject.toml"
    if not pyproject_path.is_file():
        return {}
    try:
        data = toml.load(pyproject_path)
    except (OSError, toml.TomlDecodeError):
        return {}
    return data.get("project", {}) or {}


def _names_from_people(entries: Iterable[Any] | None) -> list[str]:
    names: list[str] = []
    if not entries:
        return names
    for entry in entries:
        if isinstance(entry, dict):
            name = entry.get("name")
            if name:
                names.append(name)
        elif isinstance(entry, str):
            entry = entry.strip()
            if entry:
                names.append(entry)
    return names


project_metadata = _load_project_metadata()
project = project_metadata.get("name", "sphinx-test-docs")
version = project_metadata.get("version", "0.0.0")
release = version

author_names = _names_from_people(project_metadata.get("authors"))
contributor_names = _names_from_people(project_metadata.get("contributors"))

author_source = author_names or contributor_names
author = ", ".join(author_source) if author_source else "Unknown"

copyright_names = list(author_names)
for contributor in contributor_names:
    if contributor not in copyright_names:
        copyright_names.append(contributor)
if not copyright_names:
    copyright_names.append("Unknown")
copyright = f"{datetime.utcnow().year}, {', '.join(copyright_names)}"


extensions = [
    'sphinx_autoindex',
    'myst_parser',
    'sphinx_rtd_theme',
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx_copybutton',
    'sphinxemoji.sphinxemoji',
    'sphinx-prompt',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.graphviz',
    'sphinx.ext.todo'
]

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'restructuredtext',
    '.md': 'markdown',
}

project_directory = src_path.walk()[1][0]  # Get the first folder in src
package_toindex = str(src_path / project_directory) # Get the project src folder

sai_autodoc_global_config = {
    "members":{},
    "undoc-members":True,
    "show-inheritance":True,
    "inherited-members":True,
    "exclude-members":{},
    "special-members":{},
    "private-members":{},
}

sai_autodoc_specific_config = {
    "sphinx_test_docs.test_abc": {
        "no-index": True
    }
}


templates_path = ['_templates']
exclude_patterns = []

# Template configuration
html_theme = 'sphinx_rtd_theme'
#html_static_path = ['_static']
#html_logo = '_static/logo2.png'
#html_favicon = '_static/logo1.png'
html_show_sphinx = False
html_theme_options = {
    'logo_only': False,
    #'style_nav_header_background': '#e65e26',
    'version_selector': True
}

# Graphviz configurations
graphviz_output_format = 'svg'

# Suppress Warning generated by missing pydantic documentation
suppress_warnings = [""]


extension_list_str = ", ".join(extensions)

# Define rst_epilog to do substitutions
rst_epilog = """
.. |project_name| replace:: {project}
.. |version| replace:: {version}
.. |author| replace:: {author}
.. |extension_list| replace:: {extension_list}
""".format(project=project, version=version, author=author, extension_list=extension_list_str)

#def setup(app):
#    app.add_css_file('css/custom.css')
